import Link from "next/link";
import { ScanLine, Landmark, ShieldCheck, Users, Layers } from "lucide-react";
import { DEMO } from "@/lib/demo";
import { PositionMetrics } from "@/components/position-metrics";
import { FAQ } from "@/components/faq";
import { SEPOLIA_EXPLORER_TX, REGISTRY_ADDRESS } from "@/lib/constants";

export default function HomePage() {
  return <div className="mx-auto max-w-6xl px-6 sm:px-10">
    <section className="grid items-center gap-12 py-16 lg:grid-cols-[1.2fr_1fr] lg:py-24">
      <div><p className="mb-5 text-sm text-cut">Cashflow-backed lending. One shared limit.</p><h1 className="font-display text-5xl leading-[1.06] tracking-tight sm:text-6xl">Finance real cashflows across chains.<br /><span className="text-cut">Never twice.</span></h1><p className="mt-6 max-w-lg text-lg leading-relaxed text-ink-soft">Prove a locked cashflow on Ethereum. Finance it on Creditcoin. Give every lender the same view of what remains.</p><div className="mt-8 flex flex-wrap items-center gap-5"><Link href="/verify" className="bg-ink px-6 py-3 text-sm text-bone">Try the live demo</Link><Link href="/docs" className="text-sm underline underline-offset-4">Read the documentation</Link></div><p className="mt-4 text-xs text-ink-soft">Live testnet contracts. Explore without connecting a wallet.</p></div>
      <div className="border-l-2 border-cut pl-5 sm:pl-7"><p className="mb-4 text-sm">Sablier stream #{DEMO.streamId}</p><PositionMetrics claimId={DEMO.claimId} /><p className="mt-4 text-xs leading-relaxed text-ink-soft">Current on-chain capacity. Refreshed from the deployed registry, independent of your wallet.</p></div>
    </section>
    <section id="what" className="grid gap-7 border-t border-line py-14 md:grid-cols-[1fr_1.4fr]"><div><p className="text-sm text-cut">What is Notch?</p><h2 className="mt-3 font-display text-4xl">One cashflow.<br />One shared limit.</h2></div><p className="self-center text-lg leading-relaxed text-ink-soft">Notch is a conservation layer for cashflow-backed lending. It turns a verified source position into a claim whose financing capacity is shared across lenders on Creditcoin.</p></section>
    <section id="why" className="grid gap-7 border-t border-line py-14 md:grid-cols-[1fr_1.4fr]"><div><p className="text-sm text-cut">Why it matters</p><h2 className="mt-3 font-display text-4xl">The asset moves.<br />The limit must hold.</h2></div><div className="space-y-4 text-ink-soft leading-relaxed"><p>Lenders who cannot see each other’s commitments can finance the same future cashflow twice. A new chain should not make an already-financed position look untouched.</p><p>Notch keeps one enforceable record. Every successful loan consumes capacity. Every lender faces the same remaining limit.</p></div></section>
    <section id="who" className="border-t border-line py-14"><p className="text-sm text-cut">Who it is for</p><h2 className="mt-3 font-display text-4xl">Credit needs a common record.</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{[[Users,"Lenders & underwriters","Assess a verifiable source and see existing financing before committing funds."],[Layers,"Creditcoin’s credit ecosystem","Build lending venues around shared, enforceable capacity rather than isolated balance sheets."]].map(([Icon,title,copy])=>{const I=Icon as typeof Users;return <div className="panel p-7" key={String(title)}><I size={24} strokeWidth={1.5} className="text-cut" /><h3 className="mt-5 font-display text-2xl">{String(title)}</h3><p className="mt-3 text-sm leading-relaxed text-ink-soft">{String(copy)}</p></div>;})}</div></section>
    <section id="how" className="border-t border-line py-14"><p className="text-sm text-cut">How it works</p><h2 className="mt-3 font-display text-4xl">From a proven source to a shared balance.</h2><div className="mt-9 grid gap-8 md:grid-cols-3">{[{Icon:ScanLine,title:"Verify the source",copy:"Attestcoin proves inclusion. The registry decodes the successful Sablier receipt and validates its locked deposit."},{Icon:Landmark,title:"Finance a share",copy:"The venue transfers ccUSD to the borrower and consumes capacity in one atomic Creditcoin transaction."},{Icon:ShieldCheck,title:"Enforce what remains",copy:"Another lender sees the same balance. A draw that exceeds available capacity reverts on-chain."}].map(({Icon,title,copy})=><div key={title}><Icon size={24} strokeWidth={1.5} className="text-cut" /><h3 className="mt-4 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-relaxed text-ink-soft">{copy}</p></div>)}</div><div className="mt-10 flex flex-wrap items-center justify-between gap-6 border border-line p-6"><div><h3 className="font-display text-2xl">Inspect the evidence.</h3><p className="mt-2 text-sm text-ink-soft">The source, registry and transaction history are public.</p></div><div className="flex flex-wrap gap-5 text-sm underline underline-offset-4"><a href={SEPOLIA_EXPLORER_TX(DEMO.sourceTx)} target="_blank" rel="noreferrer">Sepolia source</a><a href={`https://creditcoin-testnet.blockscout.com/address/${REGISTRY_ADDRESS}`} target="_blank" rel="noreferrer">Creditcoin registry</a><Link href={`/activity/${DEMO.claimId}`}>Live activity</Link></div></div></section>
    <section className="grid gap-8 border-t border-line py-14 md:grid-cols-[1fr_1.4fr]"><h2 className="font-display text-4xl">A debt carved in wood.<br />A record both sides held.</h2><div><p className="leading-relaxed text-ink-soft">Tally sticks recorded obligations with notches. Split the stick, and each party held matching evidence. Notch takes its name from that shared record: every draw leaves a mark everyone can check.</p><Link href="/docs#boundaries" className="mt-5 inline-block text-sm underline underline-offset-4">Understand the scope of the guarantee</Link></div></section>
    <FAQ />
  </div>;
}

