// GENERATED by scripts/generate-web-abis.mjs from contracts/src/AttestedCashflowRegistry.sol -- do not hand-edit.
export const AttestedCashflowRegistryAbi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "decoderAddress",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "approvedDemoAssetAddress",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "ccUSDAddress",
        "type": "address"
      },
      {
        "internalType": "uint8",
        "name": "depositDecimals",
        "type": "uint8"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "AmountNotPositive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CancelableNotAllowed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ChainKeyMismatch",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ClaimAlreadyActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ClaimExpired",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ClaimNotActive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "CliffNotFuture",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "DepositNotPositive",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "EventNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "InsufficientFinancingCapacity",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "NotOwner",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "OnlyVenue",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "ReceiptNotSuccess",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "SourceContractNotAllowlisted",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TokenNotApproved",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "TransferableNotAllowed",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnlockAmountsNotZero",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnsupportedTransactionType",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VenueImmutable",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "VerificationFailed",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint128",
        "name": "originalCapacity",
        "type": "uint128"
      },
      {
        "indexed": false,
        "internalType": "uint40",
        "name": "lockedUntil",
        "type": "uint40"
      }
    ],
    "name": "ClaimInstantiated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "venue",
        "type": "address"
      }
    ],
    "name": "VenueSet",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "ALLOWLISTED_SABLIER_LOCKUP",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "CREATE_LOCKUP_LINEAR_STREAM_TOPIC0",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "EXPECTED_CHAIN_KEY",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "approvedDemoAsset",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      }
    ],
    "name": "available",
    "outputs": [
      {
        "internalType": "uint128",
        "name": "",
        "type": "uint128"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      }
    ],
    "name": "borrowerOf",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "claims",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      },
      {
        "internalType": "uint32",
        "name": "sourceChainKey",
        "type": "uint32"
      },
      {
        "internalType": "bytes32",
        "name": "sourceTxHash",
        "type": "bytes32"
      },
      {
        "internalType": "address",
        "name": "sourceContract",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "streamId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "asset",
        "type": "address"
      },
      {
        "internalType": "uint128",
        "name": "originalCapacity",
        "type": "uint128"
      },
      {
        "internalType": "uint128",
        "name": "financedCapacity",
        "type": "uint128"
      },
      {
        "internalType": "uint40",
        "name": "lockedUntil",
        "type": "uint40"
      },
      {
        "internalType": "bool",
        "name": "active",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      },
      {
        "internalType": "uint128",
        "name": "amount",
        "type": "uint128"
      }
    ],
    "name": "consume",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "decoder",
    "outputs": [
      {
        "internalType": "contract IEvmV1Decoder",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "chainKey",
        "type": "uint32"
      },
      {
        "internalType": "uint64",
        "name": "headerNumber",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "txBytes",
        "type": "bytes"
      },
      {
        "internalType": "bytes32",
        "name": "realSourceTxHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "requestedStreamId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "merkleRoot",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "hash",
            "type": "bytes32"
          },
          {
            "internalType": "bool",
            "name": "isLeft",
            "type": "bool"
          }
        ],
        "internalType": "struct INativeQueryVerifier.MerkleProofEntry[]",
        "name": "siblings",
        "type": "tuple[]"
      },
      {
        "internalType": "bytes32",
        "name": "lowerEndpointDigest",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32[]",
        "name": "continuityRoots",
        "type": "bytes32[]"
      }
    ],
    "name": "instantiateClaim",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "claimId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "owner",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "name": "setVenue",
    "outputs": [],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "venue",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;
